# Project information
site_name: 'Advanced RecyclerView'
site_description: 'Documentation site for Advanced RecyclerView (https://github.com/h6ah4i/android-advancedrecyclerview)'
site_author: 'Haruki Hasegawa'
site_url: 'https://advancedrecyclerview.h6ah4i.com/'

# Documentation and theme
docs_dir: 'docs'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/h6ah4i/android-advancedrecyclerview'
edit_uri: tree/gh-pages-source/docs

# Copyright
copyright: 'Copyright &copy; 2017 Haruki Hasegawa'

# Theme
theme:
  name: 'material'
  custom_dir: 'theme'
  favicon: 'favicon.ico'

extra:
  version: '0.10.0'
  palette:
    primary: 'teal'
    accent: 'deep-orange'
  author:
    github: 'h6ah4i'
    twitter: 'h6a_h4i'
  logo: 'images/header-logo.png'

# Extensions
markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
  - meta
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.gemoji
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.magiclink


# Customizations
extra_css: ['stylesheets/overrides.css']
extra_javascript: []

# Google Analytics
google_analytics:
  - 'UA-58259997-3'
  - 'auto'

# Nav
nav:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- Adapter:
    - Wrapper Adapter: 'wrapper-adapter/index.md'
    - ComposedAdapter: 'wrapper-adapter/composed-adapter.md'
    - Headers & Footers: 'wrapper-adapter/headers-footers.md'
    - Insertion & Filtering: 'wrapper-adapter/insertion-filtering.md'
    - Support adapter wrapping: 'wrapper-adapter/migrate-to-wrapped-adapter.md'
    - Examples: 'wrapper-adapter/examples.md'
- Drag & Drop:
    - Overview: 'draggable/index.md'
    - Tutorial: 'draggable/tutorial.md'
    - Examples: 'draggable/examples.md'
- Swipeable:
    - Overview: 'swipeable/index.md'
    - Tutorial: 'swipeable/tutorial.md'
    - Examples: 'swipeable/examples.md'
- Expandable:
    - Overview: 'expandable/index.md'
    - Tutorial: 'expandable/tutorial.md'
    - Examples: 'expandable/examples.md'
- Advanced Examples:
    - Draggable + Swipeable: 'advanced-examples/draggable-swipeable.md'
    - Expandable + Draggable + Swipeable: 'advanced-examples/expandable-draggable-swipeable.md'
    - Expandable + Draggable with Section: 'advanced-examples/expandable-draggable-section.md'
- FAQ: 'faq.md'
- License: 'license.md'
- Javadoc: 'javadoc/index.md'
