# Project information
site_name: 'Advanced RecyclerView'
site_description: 'Documentation site for Advanced RecyclerView (https://github.com/h6ah4i/android-advancedrecyclerview)'
site_author: 'Haruki Hasegawa'
site_url: 'https://h6a.h4i.github.io/android-advancedrecyclerview'
site_favicon: 'favicon.ico'

# Documentation and theme
docs_dir: 'docs'
theme: 'material'

# Repository
repo_name: 'GitHub'
repo_url: 'https://github.com/h6ah4i/android-advancedrecyclerview'


# Copyright
copyright: 'Copyright (c) 2016 Haruki Hasegawa'

extra:
  version: '0.10.0'
  palette:
    primary: 'blue-grey'
    accent: 'orange'
  author:
    github: 'h6ah4i'
    twitter: 'h6a_h4i'

# Extensions
markdown_extensions:
  - codehilite(css_class=code)
  - admonition
  - toc:
      permalink: '#'

# Customizations
extra_css: ['stylesheets/overrides.css', 'vendor/highlight/styles/github.css']
extra_javascript: ['vendor/highlight/highlight.pack.js', 'javascripts/application.js']


# Pages
pages:
- Home: 'index.md'
- Getting Started: 'getting-started.md'
- Adapter:
    - Wrapper Adapter: 'wrapper-adapter/index.md'
    - Support adapter wrapping: 'wrapper-adapter/migrate-to-wrapped-adapter.md'
    - ComposedAdapter: 'wrapper-adapter/composed-adapter.md'
    - Headers & Footers: 'wrapper-adapter/headers-footers.md'
    - Insertion & Filtering: 'wrapper-adapter/insertion-filtering.md'
- Drag & Drop: 'draggable.md'
- Swipeable: 'swipeable.md'
- Expandable: 'expandable.md'
- Advanced Examples: 'advanced-examples.md'
- FAQ: 'faq.md'
- License: 'license.md'
